### ISSUE TITLE
WP is not updateable to 4.5

### ISSUE THREAD

**Issue by xet7** [wpsandstorm/wordpress-sandstorm#18]
_From @jevgen on May 10, 2016 3:4_

Under Sandstorm the latest version is 4.4.2 and it is not updateable to 4.5.

_Copied from original issue: dwrensha/wordpress-sandstorm#24_

**Comment by xet7** [comment]
_From @dwrensha on May 10, 2016 20:34_

Hi!

The Wordpress PHP code is in read-only app storage, so the only way to update it is through Sandstorm's usual app-update mechanism. When there is an update on the Sandstorm App Market, it will get pushed automatically to servers that have installed the Wordpress app. I don't currently have an estimate for when that will be.

You may also be interested in reading [these docs about how Sandstorm restricts network access](https://docs.sandstorm.io/en/latest/using/security-practices/#true-confinement).

**Comment by JamborJan** [comment]
The "sandstormized" Wordpress repository has been updated: https://github.com/wpsandstorm/wordpress/commit/f898ea2774be4b46c39e2454ffbd3acfb03ab10e

**Comment by JamborJan** [comment]
Hey @xet7 if you have some time, please try and pull the latest code and run a complete `vagrant-spk vm up` and `vagrant-spk dev`. You should get the latest Wordpress version 4.9.4 and the latest Wordpress importer too. Please let me know if you encounter any issues.

When everything is fine according to your test we can close this issue. There should be a final testing round when we have killed some more bugs and are ready to release a new version for the Sandstorm app market.

Thanks!

**Comment by JamborJan** [comment]
I published the final release to the Sandstorm app market as well as to github.

https://github.com/wpsandstorm/wordpress-sandstorm/releases/tag/v12

We have now the latest Wordpress version 4.9.5 as well as an up to date environment (base image, php 7.2, sqlite etc.)
