### ISSUE TITLE
WordPress APP security vulnerability issue in Sandstorm platform

### ISSUE THREAD

**Issue by xet7** [wpsandstorm/wordpress-sandstorm#24]
_From @akustolin on February 18, 2017 4:15_

Dear dwrensha,
I found a potential security vulnerability in WordPress with Sandstorm platform.
May I have your e-mail address ? 

_Copied from original issue: dwrensha/wordpress-sandstorm#30_

**Comment by xet7** [comment]
_From @dwrensha on February 18, 2017 12:24_

david@sandstorm.io

**Comment by JamborJan** [comment]
Dear @akustolin please get in touch with me via keybase chat: https://keybase.io/jamborjan. I'm interested to hear what you have found. Thanks for getting in touch with us and sorry for the long delay.

**Comment by JamborJan** [comment]
I'm closing this issue for now. If there is still something to fix after we updated the whole app, please let me know.
