### ISSUE TITLE
Build Process 

### ISSUE THREAD

**Issue by JamborJan** [wpsandstorm/wordpress-sandstorm#30]
I'd like to discuss a build process which is suitable for frequently updating Wordpress on Sandstorm. This should include as much as possible automation in the future. For the beginning we can keep it simple and do things manually.

I was thinking of something like this. As said before: most steps should be automated in the future if possible.

- [ ] New Release of WordPress is available
- [ ] Renamed old a master Branch of our [working copy of Wordpress](https://github.com/wpsandstorm/wordpress) to something like "4.9 branch"
- [ ] create a new master branch wit the latest source code
- [ ] Apply all necessary changes to the new branch to make Wordpress run on Sandstorm
- [ ] Run `vagrant-spk dev` and do some testing
- [ ] If that seems to work do `vagrant-spk pack` 
- [ ] Creat draft of release on Github, add changelog
- [ ] Do some more detailed testing according to checklist (needs to be created)
- [ ] Send SPK to some more testers
- [ ] If all Ok release to app store
- [ ] Create final release on Github

Any thoughts?

**Comment by ocdtrekkie** [comment]
Feel free to send test versions to the app store. I won't approve them unless they work, and can hold until you directly tell me to approve it. Until approved, the experimental store is a great place to stash test versions you want people to try.

**Comment by JamborJan** [comment]
thanks @ocdtrekkie, sorry when I ask something which is somewhere documented and I didn't check: how can I push an app to the experimental app store?

I have created a very early version of the app which basically only contains an updated environment (stretch php7), the latest Wordpress version 4.9.4 plus plugin updates.

See: https://github.com/wpsandstorm/wordpress-sandstorm/releases/tag/v12

**Comment by ocdtrekkie** [comment]
The normal instructions to publish to the market puts stuff in experimental automatically. Https://apps.sandstorm.io/?experimental=true currently has a broken Wekan update and a broken Gogs update. :)

**Comment by JamborJan** [comment]
I tried to publish the app to the experimental market. Unfortunately it didn't work.

```
talking to index server...
curl: (6) Could not resolve host: alpha-api.sandstorm.io
curl failed
Connection to 127.0.0.1 closed.
Command failed with a non-zero exit status (1).
```

The host URL `alpha-api.sandstorm.io` resolves for me to `107.178.223.140` which seems to be down, at least a ping gets a time out.

**Comment by ocdtrekkie** [comment]
Hmmm. Cem managed to push his Gogs release yesterday, so I don't believe it is currently broken.

**Comment by JamborJan** [comment]
Hmmm, today it worked, maybe a hickup somewhere in between. PLease don't push to the main store yet. We will add more fixes but it would be cool if some people would test the build as the whole environment has been updated as well as Wordpress itself. Thanks!

**Comment by ocdtrekkie** [comment]
I am going to send a mailing list post about some of the new updates lately, I'll mention a desire for people to test it.

**Comment by ocdtrekkie** [comment]
What's the status of this being publishable? #32 would be regression from the old version, so that should probably be fixed first.

**Comment by JamborJan** [comment]
#32 has been fixed with https://github.com/wpsandstorm/wordpress/commit/0ceea2c481254b089a889bcaf1bde350268b17d9

new beta release with this fix has been uploaded to github and pushed to the Sandstorm alpha app market. More quick fixes will be applied and then we can do the testing for a release candidate.

**Comment by JamborJan** [comment]
The current process of creating new wordpress packages for sandstorm includes a lot of manual tasks but it's documented here and we should be able to have quicker and frequenter updates now: https://github.com/wpsandstorm/wordpress-sandstorm/wiki

If anybody is able to help automate this process I'm very happy to learn something :-)
